export const totalActionTypes = {
  TOTAL_INCOME: "TOTAL_INCOME",
  TOTAL_EXPENSE: "TOTAL_EXPENSE",
  TOTAL_BUDGET: "TOTAL_BUDGET",
  TOTAL_PERCENTAGE: "TOTAL_PERCENTAGE",
  DELETE_TOTAL: "DELETE_TOTAL"
};

export default totalActionTypes;
